"""create comments tabel

Revision ID: 67fdd0ea4958
Revises: 02b35f201ddb
Create Date: 2024-12-15 21:13:45.157272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fdd0ea4958'
down_revision: Union[str, None] = '02b35f201ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commkents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Unicode(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commkents_id'), 'commkents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commkents_id'), table_name='commkents')
    op.drop_table('commkents')
    # ### end Alembic commands ###
