"""adds post comments relatioship

Revision ID: 2f4a48af6faa
Revises: a7b576c9499d
Create Date: 2024-12-25 21:21:48.382488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f4a48af6faa"
down_revision: Union[str, None] = "a7b576c9499d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_comment_post_id", "post", ["post_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint("fk_comment_post_id", type_="foreignkey")
        batch_op.drop_column("post_id")
    # ### end Alembic commands ###
